version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  github-webscrapper:
    image: 'github-webscrapper:latest'
    build:
      dockerfile: Dockerfile
      context: .
    container_name: github-webscrapper-service
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379



